[package]
name = "anomaly"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.22.1", features = ["auto-initialize"] } # https://pyo3.rs/main/features#auto-initialize
serde = { version = "1.0.204", features = ["derive"] }